### ISSUE TITLE
Help! I think I have the correct answer but the checksum is not matching.

### ISSUE THREAD

**Issue by ngunia** [Splat/crypto_challenge#1]
If you're having trouble, here are some tips to ensure you're calculating the checksum the same way we did:

* It's an MD5 checksum

* The answers are all lower case

On *nix/OSX systems, you should get the correct checksum with:

```bash
md5 -s "YOUR_ANSWER"
```

If you'd rather just use an online tool, [this should suffice](https://www.md5hashgenerator.com/)

**Comment by Splat** [comment]
added to the readme
